In [1]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import csv
start_date = datetime(2024, 1, 1)
end_date = datetime(2027, 12, 31)
date_list = pd.date_range(start_date, end_date,freq='D')
calendar = pd.DataFrame()
calendar['date'] = date_list
calendar['years'] = calendar['date'].dt.year
calendar['quarter'] = 'Q' + calendar['date'].dt.quarter.astype(str)
calendar['month_no'] = 'M' + calendar['date'].dt.month.astype(str).apply(lambda x: '0' + x if(len(x) == 1) else x)
calendar['months'] = calendar['date'].dt.month_name()
calendar['day'] = calendar['date'].dt.strftime('%e %B %Y')
calendar['day'] = calendar['day'].str.strip()
calendar['day_name'] = calendar['date'].dt.day_name()
# calendar['week_of_year'] = calendar['date'].dt.weekofyear
calendar['week_of_year'] = calendar['date'].dt.isocalendar().week
calendar['time_id'] = calendar['years'].astype(str) + calendar['months'].apply(lambda x: x[:3].upper()) + calendar['date'].astype(str).apply(lambda x: x[-2:])
calendar['year_week'] = calendar['years'].astype(str) + calendar['week_of_year'].astype(str).apply(lambda x: '0' + x if(len(x) == 1) else x)
calendar['weeks'] = 'W' + calendar['week_of_year'].astype(str).apply(lambda x: '0' + x if(len(x) == 1) else x)
calendar['mon_yyyy'] = calendar['months'].apply(lambda x: x[:3]) + '-' + calendar['years'].astype(str)
calendar['yyyy_mm'] = calendar['years'].astype(str) + calendar['date'].dt.month.astype(str).apply(lambda x: '0' + x if(len(x) == 1) else x)
calendar['q_yyyy'] = calendar['quarter'] + '-' + calendar['years'].astype(str)
calendar['yyyyq'] = calendar['years'].astype(str) + calendar['date'].dt.quarter.astype(str)
calendar['create_by'] = 'manual'
calendar['entry_date'] = pd.Timestamp.now(tz='Asia/Bangkok').strftime('%Y-%m-%d %X.000')
calendar['update_date'] = calendar['entry_date']
calendar['deleted'] = False
calendar['date'] = calendar['date'].dt.strftime('%Y-%m-%d 00:00:00.000')
calendar['cpi_holiday'] = None
calendar['cashvan_holiday'] = None

##calendar['cpi_holiday'] = calendar['day_name'].apply(lambda x: 0 if(x == 'Sunday') else 1)
##calendar['cashvan_holiday'] = calendar['cpi_holiday']

In [2]:
output_calendar = calendar[['time_id','day','day_name','year_week','weeks','months','quarter','years','entry_date','update_date','month_no','date','mon_yyyy','yyyy_mm','q_yyyy','yyyyq','cpi_holiday','cashvan_holiday']]

In [ ]:
#output_calendar.astype({'year_week': 'int32','years':'int32','yyyy_mm':'int32','yyyyq':'int32'}).dtypes

In [3]:
output_calendar

,time_id,day,day_name,year_week,weeks,months,quarter,years,entry_date,update_date,month_no,date,mon_yyyy,yyyy_mm,q_yyyy,yyyyq,cpi_holiday,cashvan_holiday
0,2024JAN01,1 January 2024,Monday,202401,W01,January,Q1,2024,2024-01-04 11:07:02.000,2024-01-04 11:07:02.000,M01,2024-01-01 00:00:00.000,Jan-2024,202401,Q1-2024,20241,None,None
1,2024JAN02,2 January 2024,Tuesday,202401,W01,January,Q1,2024,2024-01-04 11:07:02.000,2024-01-04 11:07:02.000,M01,2024-01-02 00:00:00.000,Jan-2024,202401,Q1-2024,20241,None,None
2,2024JAN03,3 January 2024,Wednesday,202401,W01,January,Q1,2024,2024-01-04 11:07:02.000,2024-01-04 11:07:02.000,M01,2024-01-03 00:00:00.000,Jan-2024,202401,Q1-2024,20241,None,None
3,2024JAN04,4 January 2024,Thursday,202401,W01,January,Q1,2024,2024-01-04 11:07:02.000,2024-01-04 11:07:02.000,M01,2024-01-04 00:00:00.000,Jan-2024,202401,Q1-2024,20241,None,None
4,2024JAN05,5 January 2024,Friday,202401,W01,January,Q1,2024,2024-01-04 11:07:02.000,2024-01-04 11:07:02.000,M01,2024-01-05 00:00:00.000,Jan-2024,202401,Q1-2024,20241,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,2027DEC27,27 December 2027,Monday,202752,W52,December,Q4,2027,2024-01-04 11:07:02.000,2024-01-04 11:07:02.000,M12,2027-12-27 00:00:00.000,Dec-2027,202712,Q4-2027,20274,None,None
1457,2027DEC28,28 December 2027,Tuesday,202752,W52,December,Q4,2027,2024-01-04 11:07:02.000,2024-01-04 11:07:02.000,M12,2027-12-28 00:00:00.000,Dec-2027,202712,Q4-2027,20274,None,None
1458,2027DEC29,29 December 2027,Wednesday,202752,W52,December,Q4,2027,2024-01-04 11:07:02.000,2024-01-04 11:07:02.000,M12,2027-12-29 00:00:00.000,Dec-2027,202712,Q4-2027,20274,None,None
1459,2027DEC30,30 December 2027,Thursday,202752,W52,December,Q4,2027,2024-01-04 11:07:02.000,2024-01-04 11:07:02.000,M12,2027-12-30 00:00:00.000,Dec-2027,202712,Q4-2027,20274,None,None
1460,2027DEC31,31 December 2027,Friday,202752,W52,December,Q4,2027,2024-01-04 11:07:02.000,2024-01-04 11:07:02.000,M12,2027-12-31 00:00:00.000,Dec-2027,202712,Q4-2027,20274,None,None

In [4]:
output_calendar.to_csv('caldendar.csv',index=False,quoting=csv.QUOTE_NONNUMERIC)